spring:
  datasource:
    datacore:
      jdbc-url: 'jdbc:mariadb://10.33.194.25:4306/mlob_test?characterEncoding=UTF-8&serverTimezone=UTC'
#      jdbc-url: 'jdbc:mariadb://10.33.194.25:4306/bdp_test2?characterEncoding=UTF-8&serverTimezone=UTC'
      username: platform
      password: bigdataP1!
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate.format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
